### ISSUE TITLE
生成Config.ini 异常

### ISSUE THREAD

**Issue by CaterMaoZi** [PLFJY/bp-sys-wpf#4]
软件版本: 3.1.2
系统版本: Windows 11

在第一次启动软件时显示配置文件加载错误，缺少Resource下的Config.ini文件，已生成默认文件，请重启此软件。
重启后还是显示该提示，实测为Config.ini并没有被生成

**Comment by CaterMaoZi** [comment]
问题应该是在缺少"./Resource"路径时 不会补全Resource路径

**Comment by PLFJY** [comment]
好的，了解，将在下一个版本解决

**Comment by PLFJY** [comment]
在新的发行版中解决了https://github.com/PLFJY/bp-sys-wpf/releases/tag/V4.0.0
